config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "events#index"

   resources :events
   resources :users, only: [:show]
   resources :admissions, only: [:new]   
   resources :invites, only: [:new, :create]

end

app/models/admission.rb
class Admission < ApplicationRecord
    belongs_to :attendee, class_name: 'User'
    belongs_to :event_attended, class_name: 'Event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord

    belongs_to :creator, class_name: 'User'
    has_many :admissions, foreign_key: :event_attended_id
    has_many :attendees, through: :admissions

    has_many :invites
    has_many :invitees, through: :invites

    scope :past, -> { where("date < ?", Time.now)}
    scope :future, -> { where("date > ?", Time.now)}
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :event
    belongs_to :invitee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  validates :user_name, presence: true, uniqueness: true, length: {minimum:3, maximum:15}
  has_many :events, foreign_key: 'creator_id'

  has_many :admissions, foreign_key: 'creator_id'
  has_many :attended_events, through: :admissions, source: :event_attended

  has_many :invitees, foreign_key: :invitee_id

end

app/controllers/admissions_controller.rb
class AdmissionsController < ApplicationController
    def new
        @event = Event.find(params[:event_id])
        if @event.attendees.include?(current_user)
          flash[:error] = "You are already attending: #{@event.title}"
        else
          @event.attendees << current_user
          flash[:success] = "You are now attending happening: #{@event.title}"
        end
        redirect_to event_path(@event.id)
      end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
 before_action :authenticate_user!, only: [:new, :create]
  def new
    @event = Event.new
  end
  
  def index
      @events = Event.all
  end
  
  def create
      @event = current_user.events.build(event_params)
      if @event.save
        flash[:success] = "Event successfully created"
        redirect_to root_path
      else
        flash[:error] = "Something went wrong"
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end
  
  private

  def event_params
    params.require(:event).permit(:title,:description, :location, :date)
  end
       
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    def new
        @invite = Invite.new
      end
    
      def create
        @event = Event.find(params[:event_id])
        @user = User.find(params[:user_id])
    
        @event.invitees << @user
        flash[:success] = "#{@user.user_name} is now invited."
    
        redirect_to event_path(@event.id)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/admissions_helper.rb
module AdmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |e| %>
    <%= e.label :title, "Event title:" %>
    <%= e.text_field :title %>
    <%= e.label :date, "Date:" %>
    <%= e.date_field :date %>
    <%= e.label :location, "Location:" %>
    <%= e.text_field :location %>
    <%= e.label :description, "Description" %>
    <%= e.text_area :description %>
    <%= e.submit "Submit" %>
<% end %>

app/views/events/index.html.erb
<%= link_to "New event", new_event_path %>
<h1>Events:</h1>
<% @events.future.each do |event| %>
<b><%= link_to event.title, event %></b><br>
<%= event.description %><br>
<%= event.location %><br>
<%= event.date.strftime("%d/%m/%Y") %><br>
<% end %>
<h1>Past Events</h1>
<% @events.past.each do |event| %>
<b><%= link_to event.title, event %></b><br>
<%= event.description %><br>
<%= event.location %><br>
<%= event.date.strftime("%d/%m/%Y") %><br>
<% end %>

app/views/events/new.html.erb
<h2>Make a new event</h2>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<% e = @event %>
<h3><%= e.title %></h3>
<%= e.description %><br>
<%= e.location %><br>
<%= e.date.strftime("%d/%m/%Y") %><br>
<%= link_to e.creator.user_name, e.creator %>
<h3>Attendees for this Happening:</h3>
<ul><% e.attendees.each do |a| %></ul>
    <li><%= link_to a.user_name, a %></li>
    <% end %>
          <% if user_signed_in? %>
      <div class="link-btn attend-btn"><%= link_to "Attend Happening", new_admission_path(:event_id => e.id) %></div>
      <% end %>
      
<h3>Invite members to your happening:</h3>
<%= form_with url: invites_path do |i| %>
<%= i.collection_select :user_id, User.order(:user_name), :id, :user_name %>
<%= i.submit "Invite member", class: "link-btn" %>
<% end %>
    
<%= link_to "Home page", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users:</h1>
<% u = @user %>
<h2>Events by: <%= u.user_name %></h2>
<ul>
<% event_count = 1 %>
<% u.events.each do |event| %>
<li> <%= event_count %>, <%= event.title %></li>
<% event_count +=1 %>
<% end %>
</ul>